FROM python:3.9
ENV PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  POETRY_VERSION=1.0.0 \
  PYTHONPATH=":/src/"

# Install postgres packages
RUN pip install psycopg2

# Main project directory in the container
RUN mkdir /src
WORKDIR /src

# Install poetry and project dependencies
RUN pip install "poetry==$POETRY_VERSION"
COPY poetry.lock pyproject.toml /src/

RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi