"""empty message

Revision ID: e2a0370ba235
Revises: fbfbafc02b63
Create Date: 2021-02-21 17:13:37.600752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a0370ba235'
down_revision = 'fbfbafc02b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('product', sa.Column('price_currency', sa.String(length=5), nullable=True))
    op.add_column('product', sa.Column('price_value', sa.Float(), nullable=True))
    op.alter_column('product', 'product_type_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'product', ['id'])
    op.create_unique_constraint(None, 'product_type', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_type', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.alter_column('product', 'product_type_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('product', 'price_value')
    op.drop_column('product', 'price_currency')
    op.drop_column('product', 'is_deleted')
    # ### end Alembic commands ###
